version: '3.8'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: InitialD2001!
    volumes:
      - mongodb_data:/data/db

  nodeapp:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_URL=mongodb://root:InitialD2001!@mongodb:27017/myDatabase?authSource=admin
      - JWT_SECRET=sjwtsecretgenerator
    depends_on:
      - mongodb

volumes:
  mongodb_data:
